"""Tests for ContextFilter."""


from mindmesh.config import LimitsConfig, PrivacyConfig
from mindmesh.context.collector import FileContext
from mindmesh.context.filters import ContextFilter, is_binary, is_generated_or_minified
from mindmesh.policy.file_policy import FilePolicy


def _make_filter(
    block_files: list[str] | None = None,
    block_dirs: list[str] | None = None,
    max_file_size_kb: int = 120,
    max_total_context_kb: int = 1024,
) -> ContextFilter:
    privacy = PrivacyConfig(
        block_files=block_files or [],
        block_dirs=block_dirs or [],
    )
    limits = LimitsConfig(
        max_file_size_kb=max_file_size_kb,
        max_total_context_kb=max_total_context_kb,
    )
    return ContextFilter(FilePolicy(privacy), limits)


def _fc(path: str, content: str = "hello world\n") -> FileContext:
    return FileContext(path=path, content=content, language="python", scope_type="file")


# --- policy block ---

def test_policy_blocked_file_filtered() -> None:
    f = _make_filter(block_files=["*.env"])
    passed, report = f.filter([_fc(".env")])
    assert passed == []
    assert ".env" in report.blocked_by_policy


def test_policy_blocked_dir_filtered() -> None:
    f = _make_filter(block_dirs=["node_modules"])
    passed, report = f.filter([_fc("node_modules/index.js")])
    assert passed == []
    assert "node_modules/index.js" in report.blocked_by_policy


# --- binary ---

def test_binary_file_with_null_byte_filtered() -> None:
    f = _make_filter()
    passed, report = f.filter([_fc("data.bin", "hello\x00world")])
    assert passed == []
    assert "data.bin" in report.blocked_by_binary


def test_non_ascii_text_is_not_binary() -> None:
    content = "Türkçe içerik: çğıöşü ÇĞIÖŞÜ — non-ASCII ama binary değil"
    assert is_binary(content) is False


def test_is_binary_normal_text() -> None:
    assert is_binary("def foo():\n    return 42\n") is False


# --- file size ---

def test_large_file_blocked_by_size() -> None:
    # Multi-line so avg line length stays short (avoids generated detection)
    big_content = ("x" * 100 + "\n") * 1300  # ~127 KB
    f = _make_filter(max_file_size_kb=120)
    passed, report = f.filter([_fc("big.py", big_content)])
    assert passed == []
    assert "big.py" in report.blocked_by_size


# --- total context limit ---

def test_total_limit_cuts_remaining_files() -> None:
    # Each file ~10 KB (multi-line), limit 25 KB → first 2 pass, 3rd and beyond blocked
    chunk = ("x" * 100 + "\n") * 102  # ~10.1 KB, avg line 100 chars
    files = [_fc(f"f{i}.py", chunk) for i in range(4)]
    f = _make_filter(max_total_context_kb=25)
    passed, report = f.filter(files)
    assert len(passed) == 2
    assert len(report.blocked_by_total_limit) == 2


def test_total_limit_all_blocked_when_first_exceeds() -> None:
    chunk = ("x" * 100 + "\n") * 102  # ~10.1 KB
    files = [_fc(f"f{i}.py", chunk) for i in range(3)]
    f = _make_filter(max_total_context_kb=5)
    passed, report = f.filter(files)
    assert passed == []
    assert len(report.blocked_by_total_limit) == 3


# --- generated / minified ---

def test_generated_path_filtered() -> None:
    f = _make_filter()
    passed, report = f.filter([_fc("src/generated/models.py")])
    assert passed == []
    assert "src/generated/models.py" in report.blocked_by_generated


def test_min_in_path_filtered() -> None:
    f = _make_filter()
    passed, report = f.filter([_fc("static/app.min.js")])
    assert passed == []
    assert "static/app.min.js" in report.blocked_by_generated


def test_minified_long_lines_filtered() -> None:
    long_line = "a" * 600
    content = "\n".join([long_line] * 5)
    f = _make_filter()
    passed, report = f.filter([_fc("bundle.js", content)])
    assert passed == []
    assert "bundle.js" in report.blocked_by_generated


def test_generated_header_filtered() -> None:
    content = "// auto-generated by protoc, do not edit\npackage foo\n"
    f = _make_filter()
    passed, report = f.filter([_fc("foo.go", content)])
    assert passed == []
    assert "foo.go" in report.blocked_by_generated


def test_is_generated_do_not_edit_header() -> None:
    content = "# Do not edit this file\nx = 1\n"
    assert is_generated_or_minified("foo.py", content) is True


# --- normal files pass ---

def test_normal_file_passes() -> None:
    f = _make_filter()
    fc = _fc("src/main.py", "def hello():\n    return 'world'\n")
    passed, _ = f.filter([fc])
    assert len(passed) == 1
    assert passed[0].path == "src/main.py"


# --- FilterReport counts ---

def test_filter_report_counts() -> None:
    f = _make_filter(block_files=["*.key"], max_file_size_kb=1)
    files = [
        _fc("secret.key", "should be blocked by policy"),
        _fc("big.py", ("y" * 100 + "\n") * 12),  # ~1.2 KB → size blocked, avg line 100
        _fc("ok.py", "small"),
    ]
    _, report = f.filter(files)
    assert report.total_candidates == 3
    assert report.passed == 1
    assert "secret.key" in report.blocked_by_policy
    assert "big.py" in report.blocked_by_size


# --- edge cases ---

def test_empty_input_returns_empty() -> None:
    f = _make_filter()
    passed, report = f.filter([])
    assert passed == []
    assert report.total_candidates == 0
    assert report.passed == 0


def test_all_blocked_passed_is_zero() -> None:
    f = _make_filter(block_files=["*.py"])
    files = [_fc("a.py"), _fc("b.py"), _fc("c.py")]
    passed, report = f.filter(files)
    assert passed == []
    assert report.passed == 0
    assert report.total_candidates == 3
